(lecture02:numpy)=
# Numerical Python

The ability to do basic things with numerical arrays (vectors and matrices) is extremely important in data science applications.
We do numerical algebra in Python using the [Numpy](https://numpy.org/).
Numpy is a **huge** Python library and it has a lot of details.
We are going to cover the very basics here.
When there is something specific that you want to do, the best way to figure out how to do it is to Google it.

First, let's import ``numpy``.
We typically, do it by creating a shortcut called ``np``:

In [1]:
import numpy as np

In this way you can access whatever is in ``numpy`` by going throuh ``np`` which is less characters.
Let's create a 1D numpy array from a list:

In [2]:
a = np.array([1.2, 2.0, 3.0, -1.0, 2.0])
print(a)

[ 1.2  2.   3.  -1.   2. ]


This behaves just like a vector in Matlab.
You can multiply with a number:

In [3]:
2.0 * a

array([ 2.4,  4. ,  6. , -2. ,  4. ])

In [4]:
a * 3

array([ 3.6,  6. ,  9. , -3. ,  6. ])

You can add another vector (of the same size):

In [5]:
b = np.array([1, 2, 3, 4, 5])
c = a + b
c

array([2.2, 4. , 6. , 3. , 7. ])

You can raise all elements to a power:

In [6]:
a ** 3

array([ 1.728,  8.   , 27.   , -1.   ,  8.   ])

Or you can apply a standard function to all elements:

In [7]:
np.exp(a)

array([ 3.32011692,  7.3890561 , 20.08553692,  0.36787944,  7.3890561 ])

In [8]:
np.cos(a)

array([ 0.36235775, -0.41614684, -0.9899925 ,  0.54030231, -0.41614684])

In [9]:
np.sin(a)

array([ 0.93203909,  0.90929743,  0.14112001, -0.84147098,  0.90929743])

In [10]:
np.tan(a)

array([ 2.57215162, -2.18503986, -0.14254654, -1.55740772, -2.18503986])

Notice that the functions you can use are in ``np``.
Here is how you can get how many elements you have in the array:

In [11]:
a.shape

(5,)

Also, to see if this is a 1D array (higher dimensional arrays, 2D, 3D, etc. are also possible), you can use this:

In [12]:
a.ndim

1

You access the elements of the array just like the elements of a list:

In [13]:
a[0]

1.2

In [14]:
a[1]

2.0

In [15]:
a[2:4]

array([ 3., -1.])

In [16]:
a[::2]

array([1.2, 3. , 2. ])

In [17]:
a[::-1]

array([ 2. , -1. ,  3. ,  2. ,  1.2])

You can find the minimum or the maximum of the array like this:

In [18]:
a.min()

-1.0

In [19]:
a.max()

3.0

So, notice that ``a`` is an object of a class.
The class is called ``np.ndarray``:

In [20]:
type(a)

numpy.ndarray

and ``min()`` and ``max()`` are functions of the ``np.ndarray`` class.
Another function of the class is the dot product:

In [21]:
a.dot(b)

20.2

You can achieve the same thing with the matrix multiplication operator "@":

In [22]:
a @ b

20.2

There is also a submodule called ``numpy.linalg`` which has some linear algebra functions you can apply to arrays.
For 1D arrays (aka vectors) the vector norm is a useful one:

In [23]:
np.linalg.norm(a)

4.409081537009721

In [24]:
help(np.linalg.norm)

Help on function norm in module numpy.linalg:

norm(x, ord=None, axis=None, keepdims=False)
    Matrix or vector norm.
    
    This function is able to return one of eight different matrix norms,
    or one of an infinite number of vector norms (described below), depending
    on the value of the ``ord`` parameter.
    
    Parameters
    ----------
    x : array_like
        Input array.  If `axis` is None, `x` must be 1-D or 2-D, unless `ord`
        is None. If both `axis` and `ord` are None, the 2-norm of
        ``x.ravel`` will be returned.
    ord : {non-zero int, inf, -inf, 'fro', 'nuc'}, optional
        Order of the norm (see table under ``Notes``). inf means numpy's
        `inf` object. The default is None.
    axis : {None, int, 2-tuple of ints}, optional.
        If `axis` is an integer, it specifies the axis of `x` along which to
        compute the vector norms.  If `axis` is a 2-tuple, it specifies the
        axes that hold 2-D matrices, and the matrix norms of these

## Questions
Consider the two vectors:

In [25]:
r1 = np.array([1.0, -2.0, 3.0])
r2 = np.array([2.0, 2.0, -3.0])

Use numpy functionality to:
+ Find a unit vector in the direction of ``r1``:

In [ ]:
# Your code here

+ Find the angle between ``r1`` and ``r2`` in radians:

In [ ]:
# Your code here

+ The projection of ``r2`` on ``r1``:

In [ ]:
# Your code here

+ Use [numpy.cross](https://numpy.org/doc/stable/reference/generated/numpy.cross.html) to find the cross product between ``r2`` and ``r1``. Then, verify numerically (using numpy functionality) that $\vec{r}_1\cdot\left(\vec{r}_1\times\vec{r}_2\right) = 0$.

In [ ]:
# Your code here